name: chupp
description: chupp App
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  auto_route: ^7.4.0
  draggable_menu: ^4.0.1
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.3.6
  google_fonts: ^5.0.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true