name: chupp
description: chupp App
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  auto_route: ^7.4.0
  draggable_menu: ^4.1.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.3.6
  google_fonts: ^5.0.0
  path_provider: ^2.0.15
  font_awesome_flutter: ^10.4.0
  rive: ^0.7.16
  loading_animation_widget: ^1.2.0+4
  intl: ^0.18.1
  image_picker: ^1.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/rive/chupp-title/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true